# This deployment will be BLOCKED by Azure Policy
# Use this to demonstrate security enforcement in AKS Automatic

apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - name: app
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
